_meta:
  diubah_via: web
  diubah_pada: 2026-08-06T07:28:31+08:00
balok:
  B1:
    b_mm: 300
    deskripsi: Balok induk 300x600
    h_mm: 600
    sengkang:
      dia: 10
      hook_sudut: 135
      jarak_lapangan_mm: 200
      jarak_tumpuan_mm: 150
      kaki: 2
      bengkokan: {90: 3, 135: 2}
    tulangan:
    - dia: 19
      jumlah: 4
      posisi: atas
      tumpuan_kedua_ujung: true
    - dia: 19
      jumlah: 3
      posisi: bawah
      tumpuan_kedua_ujung: true
    - dia: 13
      jumlah: 2
      posisi: pinggang
      tumpuan_kedua_ujung: true
  B2:
    b_mm: 250
    deskripsi: Balok anak 250x500
    h_mm: 500
    sengkang:
      dia: 10
      hook_sudut: 135
      jarak_lapangan_mm: 150
      jarak_tumpuan_mm: 100
      kaki: 2
      bengkokan: {90: 3, 135: 2}
    tulangan:
    - dia: 16
      jumlah: 3
      posisi: atas
      tumpuan_kedua_ujung: true
    - dia: 16
      jumlah: 2
      posisi: bawah
      tumpuan_kedua_ujung: true
  B3:
    b_mm: 250
    deskripsi: balok atap
    h_mm: 450
    sengkang:
      dia: 10
      hook_sudut: 135
      jarak_lapangan_mm: 150
      jarak_tumpuan_mm: 100
      kaki: 2
      bengkokan: {90: 3, 135: 2}
    tulangan:
    - dia: 16
      jumlah: 3
      posisi: atas
      tumpuan_kedua_ujung: true
